deploymentMode: SingleBinary

loki:
  auth_enabled: false

  commonConfig:
    replication_factor: 1

  storage:
    type: filesystem
  storage_config:
    filesystem:
      directory: /var/loki

  schemaConfig:
    configs:
      - from: "2025-01-01"
        store: tsdb
        object_store: filesystem
        schema: v13
        index:
          prefix: loki_index_
          period: 24h

# Disable all components not used in SingleBinary mode
write:
  replicas: 0

read:
  replicas: 0

backend:
  replicas: 0

singleBinary:
  replicas: 1
  persistence:
    enabled: true
    storageClass: local-storage
    size: 5Gi

# Caching
chunksCache:
  enabled: false
resultsCache:
  enabled: false
