apiVersion: v1
kind: PersistentVolume
metadata:
  name: tempo-db
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /var/tempo
    type: DirectoryOrCreate
  storageClassName: tempo-storage
